# Generated by Django 5.0.3 on 2024-04-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("django_observe", "0002_alter_event_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="timestamp",
            field=models.DateTimeField(db_index=True),
        ),
    ]
